### ISSUE TITLE
Implement as TUI

### ISSUE THREAD

**Issue by fullerzz** [fullerzz/github-feed#4]
Now that the foundations have been coded, the next steps are to create a TUI with [`textual`](https://github.com/Textualize/textual).

### Tasks

- [x] Implement home screen
- [x] Implement releases screen
- [x] Implement starred repos screen

**Comment by fullerzz** [comment]
Remaining work for this initial TUI MVP includes tidying up the home screen and applying initial unified styling.
